<<<<<<< HEAD
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
>>>>>>> 23cbf5b64ce170239192cb65a08c83a88c726b9b

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Clerk Next.js Quickstart",
=======
  title: "Create Next App",
>>>>>>> 23cbf5b64ce170239192cb65a08c83a88c726b9b
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex min-h-screen flex-col">
              <main className="flex-1">{children}</main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
>>>>>>> 23cbf5b64ce170239192cb65a08c83a88c726b9b
  );
}
