import "./globals.css";
import { ThemeProviderWrapper } from "@/components/theme-provider-wrapper";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
       
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProviderWrapper>
              <div className="flex min-h-screen flex-col">
                <main className="flex-1">{children}</main>
              </div>
            </ThemeProviderWrapper>
          </body>
        </html>
      
    </ClerkProvider>
  );
}
